### ISSUE TITLE
'Object reference not set' error, in version 1.0.17.0

### ISSUE THREAD

**Issue by ahmadnazir** [Penneo/sdk-net#14]
With version 1.0.17.0 of Penneo.dll, the following error is thrown:

```
Object reference not set to an instance of an object.
   at Penneo.Util.ReflectionUtil.ConvertToType(Type type, Object value)
   at Penneo.Util.ReflectionUtil.SetPropertiesFromDictionary(Object obj, Dictionary`2 values)
   at Penneo.Util.ReflectionUtil.SetPropertiesFromJson(Object obj, String json)
   at Penneo.Connector.ApiConnector.WriteObject(Entity obj)
   at Penneo.Entity.Persist()
   at Mep.Bureau.Modules.ClientModule.Source.Model.Modules.Tabs.DigitalSignatureTab.Model.PenneoService.CreateCaseFile(String title, Nullable`1 sendAt, Nullable`1 expireAt, String metaData) in 
xxxxxx\PenneoService.cs:line 84
```
Code:
``` 
var caseFile = new CaseFile(title)
         {
             SendAt = sendAt,
             ExpireAt = expireAt,
             MetaData = metaData
         };
```

This works for version 1.0.15.1

**Comment by chrsadk** [comment]
I think this issue can be closed?

**Comment by janflora** [comment]
@chrsadk Was the fix part of the pull request called "Bundle"?

Remember to mention the issues that are fixed when creating a pull request. You can do it by writing "Fixes #[issue_id], Fixes #[another_issue_id] in the PR message text. Then the issues will automatically be closed when the PR is merged.

**Comment by janflora** [comment]
@chrsadk What is your verdict. Can we close this?

**Comment by chrsadk** [comment]
Yes, it can be closed.
